### PR TITLE
Initiate readthedocs

### PR DESCRIPTION
**Pull request by duc89**
* Add initial src for readthedocs with doxygen: `.readthedocs.yaml` + `docs` dir
https://multiverseframework.readthedocs.io/en/docs/index.html
https://multiverseframework.readthedocs.io/en/docs/doxygen_generated/html/index.html

* `MultiverseFramework` readthedocs proj
https://readthedocs.org/projects/multiverseframework
-> Currently has 2 active builds for `main` branch (default) and `docs` branch (this PR)
-> Each time updates to docs (.rst, .md) or source comments (.cpp, .py, etc.) are pushed `main` branch (eg by a PR merge), it will automatically trigger a build then update the corresponding contents in the above readthedocs links.
-> A manual build can be also done

Notes:
* Videos hosted on git-lfs seems to be not supported for viewing in readthedocs (or html in general), so are added as normal files at `docs/source/_static/videos`
https://stackoverflow.com/questions/47246915/cannot-embed-git-lfs-mp4-files-in-html-page-video-tag
https://github.com/git-lfs/git-lfs/issues/2725

Refs:
https://docs.readthedocs.io/en/stable/tutorial/index.html
https://www.sphinx-doc.org/en/master
https://exhale.readthedocs.io/en/latest/mastering_doxygen.html
https://breathe.readthedocs.io
https://myst-parser.readthedocs.io

Ref proj:
https://github.com/readthedocs-examples/example-sphinx-basic/tree/main
https://rapyutasimulationplugins.readthedocs.io/en/devel
https://medium.com/@oliver.k.ernst/c-documentation-with-doxygen-cmake-sphinx-breathe-for-those-of-use-who-are-totally-lost-7d555386fe13

### CODE REVIEW

**Comment by Tadinu** [comment]
Thanks for the merge. Could you provide a readthedocs account email, to be added as the maintainer?
https://readthedocs.org/projects/multiverseframework

**Comment by duc89** [comment]
Thanks for the merge. Could you provide a readthedocs account email, to be added as the maintainer?
https://readthedocs.org/projects/multiverseframework

**Comment by duc89** [comment]
@HoangGiang93 Thanks for the merge. Could you provide a readthedocs account email, to be added as the maintainer?
https://readthedocs.org/projects/multiverseframework

**Comment by HoangGiang93** [comment]
hoanggia@uni-bremen.de

**Comment by duc89** [comment]
image
Seems not existing yet?

**Comment by HoangGiang93** [comment]
I just registered, thank you

**Comment by duc89** [comment]
Yeah so an invitation was sent to your email, after confirmation you should be able to trigger builds there.

**Pull request merged**
